const val GROCERIES_TELEGRAM_BOT_TOKEN_KEY = "GROCERIES_TELEGRAM_BOT_TOKEN"
const val EXPENSES_TELEGRAM_BOT_TOKEN_KEY = "EXPENSES_TELEGRAM_BOT_TOKEN"

const val NOTION_TOKEN_KEY = "NOTION_TOKEN"
const val PRODUCTS_DATABASE_KEY = "PRODUCTS_DATABASE"
const val NEED_TO_BUY_DATABASE_KEY = "NEED_TO_BUY_DATABASE"

const val GI_TRAINING_LIST_PAGE_KEY = "GI_TRAINING_LIST_PAGE"
const val NO_GI_TRAINING_LIST_PAGE_KEY = "NO_GI_TRAINING_LIST_PAGE"
const val EXPENSES_DATABASE_KEY = "EXPENSES_DATABASE"
const val REGULAR_EXPENSES_DATABASE_KEY = "REGULAR_EXPENSES_DATABASE"
const val CURRENCY_DATABASE_KEY = "CURRENCY_DATABASE"
const val RUB_TO_USD_PAGE_KEY = "RUB_TO_USD_PAGE"
const val RUB_TO_EUR_PAGE_KEY = "RUB_TO_EUR_PAGE"